### ISSUE TITLE
infinite login loop in step 1

### ISSUE THREAD

**Issue by fhinkel** [OfficeDev/m365-msteams-northwind-app-samples#42]
I followed the steps in A01 but end up with an infinite login loop here. I'm using the admin@ account. It has an employee ID and a manager. Any idea where I went wrong? I started `ngrok` with out `--host-header` because I don't have a paid subscription. 

<img width="1552" alt="Screen Shot 2022-04-19 at 9 26 00 PM" src="https://user-images.githubusercontent.com/101553/164128359-48bdac66-9ced-43c5-a43f-405df0a57a28.png">

**Comment by fhinkel** [comment]
```
This is the error I'm getting: 

{
    "errorCode": "interaction_required",
    "errorMessage": "AADSTS16000: Either multiple user identities are available for the current request or selected account is not supported for the scenario.\r\nTrace ID: 38ec1ec9-469e-43f6-81ca-b9464ec81600\r\nCorrelation ID: 14fe8ae9-a081-4c1c-9cbf-c9a52f73aed5\r\nTimestamp: 2022-04-20 13:33:08Z",
    "subError": "",
    "name": "InteractionRequiredAuthError",
    "correlationId": "14fe8ae9-a081-4c1c-9cbf-c9a52f73aed5"
}
```

**Comment by fhinkel** [comment]
<img width="1552" alt="Screen Shot 2022-04-20 at 9 38 44 AM" src="https://user-images.githubusercontent.com/101553/164243236-0891eaa8-60a2-4020-b23f-b66411ca6fdf.png">
I'm able to log in on a brand new Chrome profile. Must have been a problem with having my MS or my demo account logged in on the same Chrome profile.

**Comment by fhinkel** [comment]
Maybe add `console.log()` in the `catch` statement where I get the error so it's easier to see the problem in the debugger tools without stepping through a bunch of break points.

**Comment by BobGerman** [comment]
Hoping this is fixed? Please pull new source from the main branch or copy new copies of the files in /client/identity to test.
Thanks!

**Comment by fhinkel** [comment]
Thanks! It works on my profile with another account logged in as well.
