### ISSUE TITLE
problem with env variable name

### ISSUE THREAD

**Issue by cherchyk** [OfficeDev/m365-msteams-northwind-app-samples#82]
While working on the lab I found that "on my PC" :) `HOSTNAME` is replaced by my real system `HOSTNAME`.  

`HOSTNAME` variable defined in .env did not overwrite the real `HOSTNAME` system variable.

The problem disappeared after I changed `HOSTNAME=something.ngrok.io` to `HOSTNAME123=something.ngrok.io` and all  `process.env.HOSTNAME` to `process.env.HOSTNAME123`

**Comment by BobGerman** [comment]
Fixed in next version!
The labs will move to https://github.com/microsoft/app-camp/ - this update adds Teams JavaScript SDK v2 and has other fixes including this one, however the instructions aren't in sync just yet. To resolve this issue, HOSTNAME is now HOST_NAME in the .env file.
